### ISSUE TITLE
TODO List (Iteration ~19.11.07)

### ISSUE THREAD

**Issue by ayuusweetfish** [kawa-yoiko/botany#1]
安心期中和大作业啦~

- [x] Web 框架：HTTP 路由，数据库，sessions，cookies（@kawa-yoiko）
- [x] CI（@kawa-yoiko）
- [x] 静态的前端 demo 页面（@CyrilKZ）
