### ISSUE TITLE
TODO List (Iteration ~20.01.09)

### ISSUE THREAD

**Issue by kawa-yoiko** [kawa-yoiko/botany#12]
期末 milestone 冲鸭 (ง •̀_•́)ง

- Server
  - [x] 上传赛事 banner
  - [x] 执行对局结算脚本（@kawa-yoiko, 1.7）
- Judge
  - [x] 编译 C/C++（@kawa-yoiko, 1.6）
  - [x] 执行对局（@kawa-yoiko, 1.6-1.7）
  - [x] 完成井字棋 demo 的赛制脚本与动画（@kawa-yoiko, 1.8）
- Client
  - [x] 上传头像和赛事 banner
  - [x] 设计并实现「选择出战代码」的交互流程
  - （延后 🕊）排行榜分栏显示战绩
- Meta
  - [x] 整理文档（1.9）
