### ISSUE TITLE
TODO List (Iteration ~19.11.14)

### ISSUE THREAD

**Issue by ayuusweetfish** [kawa-yoiko/botany#2]
磨刀不误砍柴工~

- 后端
  * [x] 框架：整理并确定结构（middleware 的实现方式，是否 MVC？），~~Redis~~（@kawa-yoiko）
  * [x] 确定 URL 路由，渲染静态页面，所有链接可用（@list17）
  * [x] RESTful API 返回假数据（@a375D）
- [x] 前端：RESTful 对接（@CyrilKZ）
- [x] CI/CD：部署到 VPS（@kawa-yoiko）

Non-code
- 后端组确保了解当前 [`main.go`](https://github.com/kawa-yoiko/botany/blob/e10702ca9858215eac7a8843a01fcb9876fa3e44/app/main.go) 中的所有逻辑并完成本地环境配置
- 需要决定前后端之间数据交换格式（JSON/XML？）
