### ISSUE TITLE
TODO List (Iteration ~19.12.15)

### ISSUE THREAD

**Issue by ayuusweetfish** [kawa-yoiko/botany#8]
- Server（@list17, @a375D）
  - [x] 实现数据分页显示（@list17）
  - [x] 在比赛详情中增加管理员列表（@list17）
  - [x] 在用户主页中增加最近的比赛列表和对局列表（@list17）
  - [x] 用户个性签名支持（@list17）
  - [x] 确定赛制脚本的接口设计，开始自动创建对局（@kawa-yoiko，优先）
- Judge（@kawa-yoiko）
  - [x] 比赛 SDK demo
  - [x] 加入沙箱 ioi/isolate
- Client（@CyrilKZ）
  - [x] 完成对局列表和详情页面
  - [x] 修复已知问题（时间戳单位、编辑比赛 /edit 误写为 /create、比赛管理员列表无法为空）
